[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.14.0",
    "flake8>=7.3.0",
    "llm-sdk",
    "mypy>=2.3.1",
    "pydantic>=2.13.4",
]

[tool.uv.sources]
llm-sdk = { path = "llm_sdk" }

[tool.uv]
python-preference = "only-managed"